# Generated by Django 5.2.17 on 2026-09-22 06:22

import django.db.models.deletion
import webreview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("contract_type", models.CharField(blank=True, max_length=100)),
                ("client_role", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_extension", models.CharField(max_length=10)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size_bytes", models.PositiveBigIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to=webreview.models.contract_document_upload_path
                    ),
                ),
                ("file_hash_sha256", models.CharField(max_length=64)),
                ("is_current", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extraction_error", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="webreview.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=64, unique=True)),
                ("client_perspective", models.TextField(blank=True)),
                ("research_date", models.DateField(blank=True, null=True)),
                ("max_cycles", models.PositiveIntegerField(default=2)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "report_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Completed", "Completed"),
                            ("Provisional", "Provisional"),
                            ("Incomplete", "Incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "commercial_recommendation",
                    models.CharField(blank=True, max_length=100),
                ),
                ("correction_cycle", models.PositiveIntegerField(default=0)),
                ("current_stage_label", models.CharField(blank=True, max_length=100)),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("report_markdown", models.TextField(blank=True)),
                ("report_context", models.JSONField(blank=True, null=True)),
                (
                    "report_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=webreview.models.review_pdf_upload_path,
                    ),
                ),
                ("incomplete_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="webreview.contract",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="webreview.contractdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finding_id", models.CharField(max_length=20)),
                ("severity", models.CharField(max_length=20)),
                ("confidence", models.CharField(max_length=20)),
                ("clause_reference", models.CharField(blank=True, max_length=255)),
                ("clause_text", models.TextField(blank=True)),
                ("affected_party", models.CharField(blank=True, max_length=255)),
                ("trigger_scenario", models.TextField(blank=True)),
                ("consequence", models.TextField(blank=True)),
                ("legal_proposition", models.TextField(blank=True)),
                ("rating_rationale", models.TextField(blank=True)),
                ("recommended_amendment", models.TextField(blank=True)),
                ("fallback_position", models.TextField(blank=True)),
                ("residual_risk", models.TextField(blank=True)),
                ("missing_evidence", models.TextField(blank=True)),
                ("counterargument", models.TextField(blank=True)),
                ("status", models.CharField(default="open", max_length=20)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="webreview.review",
                    ),
                ),
            ],
            options={
                "ordering": ["finding_id"],
            },
        ),
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority_id", models.CharField(max_length=20)),
                ("authority_type", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("citation", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("pinpoint", models.CharField(blank=True, max_length=255)),
                ("application_notes", models.TextField(blank=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorities",
                        to="webreview.review",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "authorities",
                "ordering": ["authority_id"],
            },
        ),
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=50)),
                ("role", models.CharField(blank=True, max_length=50)),
                ("tier", models.CharField(blank=True, max_length=20)),
                ("provider", models.CharField(blank=True, max_length=20)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("effort_actual", models.CharField(blank=True, max_length=50)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("detail", models.TextField(blank=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="webreview.review",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposition_checked", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("identity_check", models.TextField(blank=True)),
                ("text_check", models.TextField(blank=True)),
                ("attribution_check", models.TextField(blank=True)),
                ("proposition_check", models.TextField(blank=True)),
                ("treatment_check", models.TextField(blank=True)),
                ("application_check", models.TextField(blank=True)),
                ("caveats", models.TextField(blank=True)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_records",
                        to="webreview.authority",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_records",
                        to="webreview.finding",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="contractdocument",
            constraint=models.UniqueConstraint(
                fields=("contract", "version_number"), name="unique_contract_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("review", "finding_id"), name="unique_review_finding"
            ),
        ),
        migrations.AddConstraint(
            model_name="authority",
            constraint=models.UniqueConstraint(
                fields=("review", "authority_id"), name="unique_review_authority"
            ),
        ),
    ]
