# Generated by Django 5.2.17 on 2026-09-22 16:29

import django.db.models.deletion
import webreview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webreview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=64, unique=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_stage_label", models.CharField(blank=True, max_length=100)),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("summary_context", models.JSONField(blank=True, null=True)),
                (
                    "summary_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=webreview.models.summary_pdf_upload_path,
                    ),
                ),
                ("fidelity_issues", models.JSONField(blank=True, default=list)),
                ("incomplete_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="webreview.contract",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summaries",
                        to="webreview.contractdocument",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "summaries",
                "ordering": ["-created_at"],
            },
        ),
    ]
