# Generated by Django 5.2.17 on 2026-09-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webreview", "0002_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="summary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
